"use client";

import { useParams } from "next/navigation";
import { products } from "../../../lib/catalogue";
import { addToCart } from "../../../lib/cart";

export default function ProductPage() {
  const { id } = useParams<{ id: string }>();
  const product = products.find((item) => item.id === id) ?? products[1];

  return <main className="min-h-screen bg-[#f7f4ea] text-[#171713]"><header className="border-b border-black/10 bg-[#f7f4ea] px-6 py-4 md:px-12"><div className="mx-auto flex max-w-7xl items-center justify-between"><a href="/" className="text-2xl font-black">MR. <span className="text-[#8c6d21]">EGGZ</span></a><a href="/products" className="rounded-full border border-black/10 px-5 py-2 text-sm font-bold">Back to shop</a></div></header><section className="mx-auto grid max-w-7xl gap-10 px-6 py-12 md:grid-cols-2 md:items-center md:px-12 md:py-20"><div className="flex aspect-square items-center justify-center rounded-[2.5rem] bg-[#efe8d2]"><div className="text-center"><div className="text-[8rem] font-black leading-none md:text-[11rem]">{product.quantity}</div><div className="mt-3 text-sm font-black uppercase tracking-[.3em] text-[#8c6d21]">eggs per pack</div></div></div><div><p className="text-sm font-black uppercase tracking-[.28em] text-[#8c6d21]">Mr. Eggz pack</p><h1 className="mt-4 text-5xl font-black tracking-tight md:text-7xl">{product.name}</h1><p className="mt-6 max-w-xl text-xl leading-8 text-black/60">{product.description}</p><div className="mt-8 rounded-3xl border border-black/10 bg-white p-6"><div className="flex items-center justify-between"><span className="font-bold">Pack quantity</span><span className="font-black">{product.quantity} eggs</span></div><div className="mt-4 flex items-center justify-between"><span className="font-bold">Selling price</span><span className="text-2xl font-black">₹{product.price}</span></div><div className="mt-3 flex items-center justify-between"><span className="font-bold text-black/50">MRP</span><span className="font-bold text-black/45 line-through">₹{product.mrp}</span></div><div className="mt-4 inline-flex rounded-full bg-red-50 px-3 py-1 text-xs font-black text-red-600">{product.discountLabel}</div><p className="mt-4 text-sm leading-6 text-black/50">Verified Mr. Eggz catalogue pricing.</p></div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><button onClick={() => { addToCart({ id: product.id, name: product.name, quantity: 1 }); window.location.href = "/cart"; }} className="rounded-full bg-[#171713] px-8 py-4 font-black text-white">Add to cart · ₹{product.price}</button><a href="/#business" className="rounded-full border border-black/15 px-8 py-4 text-center font-black">Bulk enquiry</a></div></div></section></main>;
}
